services:
  postgres:
    image: postgres:15-alpine
    container_name: social_network_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - social-network

  social-php:
    build: .
    container_name: social
    depends_on:
      - postgres
    volumes:
      - ./src:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - social-network

volumes:
  postgres_data:

networks:
  social-network:
    driver: bridge